### ISSUE TITLE
Gauge.CSharp.Runner always 32-bit?

### ISSUE THREAD

**Issue by tompilompa** [getgauge/gauge-csharp#111]
32-bit Gauge.CSharp.Runner is started when running the gauge command on a project that is 64-bit forced. My steps utilize the EdgeDriver which starts a MicrosoftWebDriver that launches a 64-bit MicrosoftEdge.exe. The code in the steps needs to access the native dialog inside the browser. So I am using a UI automation library which cannot attach to the 64-bit process because the runner is always in 32-bits. 

Is it possible to control this? The Gauge.CSharp.Runner.exe is build on AnyCpu but prefers 32-bit.

### Gauge version
```
Gauge version: 0.9.1

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
```

**Comment by sriv** [comment]
Yes, you are right.

This is because even though `Gauge.CSharp.csproj` is built with `AnyCPU`, the compiler assumes `Prefer32bit` to be true by default. This needs to be changed by setting it to `false` explicitly in the project file.

In the meantime, you can use `corflags` to change this behaviour:

- Open VS developer command prompt.
- `cd %appdata%\gauge\plugins\csharp\<latest version>\bin` where latest_version = 0.10.1 in your case.
- `corflags Gauge.CSharp.Runner.exe  /32bitpref- /32bitreq-`
- `cd <your gauge project>`
- `gauge run specs`

This should launch `Gauge.CSharp.Runner.exe` in 64 bit mode in a 64 bit OS.

**Comment by sriv** [comment]
Fix should be available in nightly >= 06/10/2017

**Comment by sriv** [comment]
#### Notes:

`Environment.Is64BitProcess` should fetch if the process is running as 64 bit. Something like this in the step implementation can be used to verify this:

`Console.Writeline("Is 64 bit: " + Environment.Is64BitProcess);`
