### ISSUE TITLE
Add support to capture screenshot

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-csharp#137]
Parent issue: https://github.com/getgauge/gauge/issues/632

Gauge C# API:

`GaugeScreenshots.Capture` would capture the screenshot at the instance it is invoked.

**Comment by sriv** [comment]
Should be available in nightly >= 18/07/2018

**Comment by harimadusumilli** [comment]
Hello Gauge Team,
I am unable to capture the screen shot on failure of a Test. The plugin I am using is for .Net Core
I am using the name space : using Gauge.CSharp.Lib;
[AfterScenario]
public void TearDown() {
GaugeScreenshots.Capture();
Driver.Close();
}
When the Test fails on a step, I am unable to see the screen shot in the report.
I see the following :
After Scenario Failed:
The system cannot find the file specified
[Hide details]
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at Gauge.CSharp.Lib.DefaultScreenGrabber.TakeScreenShot()
at Gauge.CSharp.Lib.GaugeScreenshots.Capture()
at Gauge.Triggers.Implementation.DriverFactory.TearDown()
Is the above a known issue and if yes, what is the fix for this ? Or is the fix being worked ?

**Comment by zabil** [comment]
@harimadusumilli 

Can you please share the output of
```
gauge -v
```

**Comment by harimadusumilli** [comment]
Hello Zabil,

Thank you for writing back to me. Sorry for the delayed response. Please find the requested information below :

gauge -v
Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
csharp (0.10.5)
dotnet (0.1.0)
html-report (4.0.6)


Thanks,
Hari

Sent from Mail for Windows 10

**Comment by sriv** [comment]
@harimadusumilli - you need the `screenshot` plugin installed. Please try the same after running `gauge install screenshot`.

Note that you are using an old version of gauge, please consider upgrading to the [latest version](https://github.com/getgauge/gauge/releases/latest)
