### ISSUE TITLE
Gauge CSharp runner should load test assembly's config file

### ISSUE THREAD

**Issue by alexbestul** [getgauge/gauge-csharp#50]
When running tests, the Gauge runner should load the test assembly's App.config file, if one is present.  This would match the behavior of the Visual Studio test tools (MSTest).

Currently, I'm working with a test harness that consumes a WCF endpoint.  The harness expects the WCF configuration to be in the config file.  I have existing tests that work fine with MSTest, but I'm unable to use Gauge unless I can supply my own config file.

I have attached a sample project that demonstrates the issue.  It includes two tests (one written using MSTest, one with Gauge) that assert the location of the config file.  Currently, the MSTest test passes, and the Gauge test fails.

[gauge-appconfig.zip](https://github.com/getgauge/gauge-csharp/files/141475/gauge-appconfig.zip)

I think the solution in this StackOverflow post could work for Gauge, but I haven't looked far enough into the code/architecture enough to attempt a fix myself:  http://stackoverflow.com/questions/1838619/relocating-app-config-file-to-a-custom-path

**Comment by sriv** [comment]
Thanks for reporting and the analysis. Will investigate.

**Comment by sriv** [comment]
@alexbestul - there should be a nightly build ready tonight, if you could try it out and check, that would be great!

**Comment by alexbestul** [comment]
I tried the 3-01 nightly build, and the test from the gauge-appconfig.zip file still failed.  Do I need to wait for the 3-02 nightly?

**Comment by sriv** [comment]
Hmm, I notice that you are explicitly asserting on the Current Appdomain's SetupInformation. 

The fix that I introduced was to use the `Load` instead of `LoadFrom` context while loading the test assembly. `Load` context uses .NET frameworks's dependency resolution and [is the recommended way](https://msdn.microsoft.com/en-us/library/dd153782(v=vs.110).aspx#Anchor_4) of loading assemblies.

Could you try simulating a `BindingRedirect` and see that your app.config is honoured? In the meanwhile, I will add another commit to explicitly set the Sandbox Appdomain's configuration file to be the `app.config` of your test project. (This should be available in the next nightly)

**Comment by sriv** [comment]
Released via [0.7.2](https://github.com/getgauge/gauge-csharp/releases/tag/v0.7.2)
